In [18]:
#import Libraries
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [19]:
#import datasets
df=pd.read_csv("C:/Users/Aman/Desktop/open cv/heart_disease_dataset.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca  thal  num  
0   0     6    0  
1   3     3    1  
2   2     7    1  
3   0     3    0  
4   0     3    0

In [20]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
num         0
dtype: int64

In [21]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.438944    0.679868    3.158416  131.689769  246.693069    0.148515   
std      9.038662    0.467299    0.960126   17.599748   51.776918    0.356198   
min     29.000000    0.000000    1.000000   94.000000  126.000000    0.000000   
25%     48.000000    0.000000    3.000000  120.000000  211.000000    0.000000   
50%     56.000000    1.000000    3.000000  130.000000  241.000000    0.000000   
75%     61.000000    1.000000    4.000000  140.000000  275.000000    0.000000   
max     77.000000    1.000000    4.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope  \
count  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.990099  149.607261    0.326733    1.039604    1.600660   
std      0.994971   22.875003    0.469794    1.161075    0.616226   
min      0.000000   71.000000    0.000000    0.000000    1.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000   
50%      1.000000  153.000000    0.000000    0.800000    2.000000   
75%      2.000000  166.000000    1.000000    1.600000    2.000000   
max      2.000000  202.000000    1.000000    6.200000    3.000000   

                  ca           thal         num  
count     303.000000     303.000000  303.000000  
mean    -1319.468647    -655.363036    0.458746  
std     11432.566205    8111.366638    0.499120  
min   -100000.000000 -100000.000000    0.000000  
25%         0.000000       3.000000    0.000000  
50%         0.000000       3.000000    0.000000  
75%         1.000000       7.000000    1.000000  
max         3.000000       7.000000    1.000000

In [22]:
X=df.iloc[:,[3,4,7]].values
y=df.iloc[:,[-1]].values
          

In [23]:
y

array([[0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
    

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.50,random_state=123, stratify=y)

In [27]:
y=y.ravel()
y_train=y_train.ravel()
y_test=y_test.ravel()
y_train

array([0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1],
      dtype=int64)

In [26]:
print("All",np.bincount(y)/float(len(y))*100.0)
print("Testing : ",np.bincount(y_test)/float(len(y_test))*100.0)
print("Training",np.bincount(y_train)/float(len(y_train))*100.0)


All [54.12541254 45.87458746]
Testing :  [53.94736842 46.05263158]
Training [54.30463576 45.69536424]


In [27]:
from sklearn.linear_model import LogisticRegression
linreg=LogisticRegression()

In [28]:
linreg.fit(X_train,y_train)

LogisticRegression()

In [29]:
y_predict=linreg.predict(X_test)
y_predict

array([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [30]:
print(np.sum(y_predict==y_test))

113


In [31]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_predict))

0.743421052631579


In [32]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_predict))

[[70 12]
 [27 43]]


In [33]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.72      0.85      0.78        82
           1       0.78      0.61      0.69        70

    accuracy                           0.74       152
   macro avg       0.75      0.73      0.74       152
weighted avg       0.75      0.74      0.74       152



In [34]:
print("Sample Correctly Classified:")
correct_idx=np.where(y_predict==y_test)[0]
correct_idx

Sample Correctly Classified:


array([  0,   1,   2,   5,  10,  11,  13,  14,  16,  17,  19,  21,  22,
        23,  24,  25,  26,  28,  29,  30,  31,  33,  34,  35,  36,  38,
        39,  40,  41,  45,  46,  47,  48,  50,  51,  52,  54,  57,  58,
        60,  61,  62,  64,  65,  68,  69,  70,  71,  72,  74,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  91,
        92,  93,  96,  97,  98,  99, 100, 101, 102, 104, 106, 107, 109,
       111, 112, 113, 114, 115, 116, 117, 118, 119, 121, 122, 123, 124,
       125, 127, 130, 131, 132, 133, 134, 135, 136, 137, 138, 140, 141,
       142, 143, 144, 145, 146, 147, 149, 150, 151], dtype=int64)

In [35]:
print("Sample Incorrectly Classified:")
incorrect_idx=np.where(y_predict!=y_test)[0]
print(incorrect_idx)

Sample Incorrectly Classified:
[  3   4   6   7   8   9  12  15  18  20  27  32  37  42  43  44  49  53
  55  56  59  63  66  67  73  75  90  94  95 103 105 108 110 120 126 128
 129 139 148]


In [36]:
plt.figure(figsize=(8,8))
plt.scatter(X[y==0,0],X[y==0,1],s=40,label=0)
plt.scatter(X[y==1,0],X[y==1,1],s=40,label=1,
            marker='s')
plt.xlabel("First Features")
plt.ylabel("Seconds Features")
plt.legend(loc="upper right");

In [37]:
from sklearn.model_selection import train_test_split
df=pd.read_csv("C:/Users/Aman/Desktop/open cv/heart_disease_dataset.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca  thal  num  
0   0     6    0  
1   3     3    1  
2   2     7    1  
3   0     3    0  
4   0     3    0

In [38]:
X=df.iloc[:,[3,4,7]].values
y=df.iloc[:,-1].values

In [39]:
y

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,

In [40]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.5,random_state=123,stratify=y)

In [41]:
y=y.ravel()
y_train=y_train.ravel()
y_test=y_test.ravel()


In [42]:
print("All",np.bincount(y)/float(len(y))*100)
print("Testing",np.bincount(y_test)/float(len(y_test))*100)
print("Traning",np.bincount(y_train)/float(len(y_train))*100)

All [54.12541254 45.87458746]
Testing [53.94736842 46.05263158]
Traning [54.30463576 45.69536424]


In [43]:
from sklearn.neighbors import KNeighborsClassifier
cls=KNeighborsClassifier(n_neighbors=10)

In [52]:
cls.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [53]:
y_predict=cls.predict(X_test)
y_predict

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
      dtype=int64)

In [54]:
print(np.sum(y_test==y_predict))

96


In [55]:
from sklearn.metrics import accuracy_score,classification_report

In [56]:
print("Accuracy: ",accuracy_score(y_test,y_predict))
print("Classification_report",classification_report(y_test,y_predict))

Accuracy:  0.631578947368421
Classification_report               precision    recall  f1-score   support

           0       0.61      0.87      0.72        82
           1       0.69      0.36      0.47        70

    accuracy                           0.63       152
   macro avg       0.65      0.61      0.59       152
weighted avg       0.65      0.63      0.60       152



In [57]:
print("Sample Corret Classified")
print(np.where(y_test==y_predict))


Sample Corret Classified
(array([  1,   2,   3,   4,   5,   9,  11,  12,  13,  14,  19,  20,  21,
        22,  24,  25,  28,  31,  33,  34,  36,  38,  40,  41,  43,  45,
        46,  48,  49,  51,  54,  58,  61,  62,  63,  64,  69,  70,  72,
        74,  77,  78,  79,  81,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  96,  97,  99, 100, 101, 104, 107, 109, 111, 113,
       114, 116, 117, 118, 119, 121, 122, 123, 124, 125, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 141, 142, 143, 144, 145, 146,
       147, 148, 149, 150, 151], dtype=int64),)


In [58]:
plt.figure(figsize=(8,8))
plt.scatter(X[y==0,0],X[y==0,1],s=40,label=0)
plt.scatter(X[y==1,0],X[y==1,1],s=40,label=1,
            marker='s')
plt.xlabel("First Features")
plt.ylabel("Seconds Features")
plt.legend(loc="upper right");

In [2]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
df=pd.read_csv("C:/Users/Aman/Desktop/open cv/heart_disease_dataset.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca  thal  num  
0   0     6    0  
1   3     3    1  
2   2     7    1  
3   0     3    0  
4   0     3    0

In [6]:
X=df.iloc[:,[3,4,7]].values
y=df.iloc[:,-1].values

In [4]:
X=X.ravel()
y=y.ravel()

In [23]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.5,random_state=123,stratify=y)

In [35]:
from sklearn.preprocessing import StandardScaler
s_c=StandardScaler()
X_train=s_c.fit_transform(X_train)
X_test=s_c.fit_transform(X_test)

In [36]:
from sklearn.tree import DecisionTreeClassifier
cls=DecisionTreeClassifier(criterion = 'entropy', random_state = 123)

In [37]:
cls.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=123)

In [38]:
y_predict=cls.predict(X_test)
y_predict

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [39]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_predict))

0.6118421052631579


In [44]:
print("Correct Sample Classified")
correct_idx=np.where(y_test==y_predict)
correct_idx

Correct Sample Classified


(array([  1,   2,   5,   7,   9,  10,  11,  12,  13,  14,  15,  17,  18,
         19,  21,  22,  23,  24,  25,  26,  29,  31,  34,  36,  37,  38,
         39,  41,  47,  48,  50,  51,  52,  60,  61,  65,  66,  68,  69,
         72,  74,  78,  79,  80,  82,  83,  84,  85,  86,  88,  89,  91,
         92,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 106, 107,
        109, 111, 113, 114, 117, 118, 119, 121, 123, 124, 125, 127, 128,
        130, 133, 135, 136, 138, 139, 140, 143, 144, 145, 146, 147, 149,
        150, 151], dtype=int64),)

In [45]:
print("Incorrect Sample Classified")
Incorrect_idx=np.where(y_test!=y_predict)
Incorrect_idx

Incorrect Sample Classified


(array([  0,   3,   4,   6,   8,  16,  20,  27,  28,  30,  32,  33,  35,
         40,  42,  43,  44,  45,  46,  49,  53,  54,  55,  56,  57,  58,
         59,  62,  63,  64,  67,  70,  71,  73,  75,  76,  77,  81,  87,
         90,  93,  94, 105, 108, 110, 112, 115, 116, 120, 122, 126, 129,
        131, 132, 134, 137, 141, 142, 148], dtype=int64),)

In [41]:
import matplotlib.pyplot as plt
plt.figure(figsize=(8,8))
plt.scatter(X[y==0,0],X[y==0,1],s=40,label=0)
plt.scatter(X[y==1,0],X[y==1,1],s=40,label=1,
            marker='s')
plt.xlabel("First Features")
plt.ylabel("Seconds Features")
plt.legend(loc="upper right");

In [48]:
for n in np.unique(y_test):
    idx=np.where(y_test==n)[0]
    plt.scatter(X_test[idx,1],X_test[idx,2],label="Class %s"% str(n))
plt.scatter(X_test[Incorrect_idx,1],X_test[Incorrect_idx,2],color='darkred',
                       s=40)    
    
plt.xlabel("sepal width[cm]")   
plt.ylabel("petal length [cm]")   
plt.legend(loc=3)
plt.title("Iris Classification Result")
plt.show()

In [3]:
import numpy as np
import pandas as pd
df=pd.read_csv("C:/Users/Aman/Desktop/open cv/heart_disease_dataset.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca  thal  num  
0   0     6    0  
1   3     3    1  
2   2     7    1  
3   0     3    0  
4   0     3    0

In [4]:
X=df.iloc[:,[3,4,7]].values
y=df.iloc[:,-1].values

In [5]:
y

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,

In [112]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.50,random_state=0,stratify=y)

In [113]:
y=y.ravel()


In [114]:
print("All: ",np.bincount(y)/float(len(y))*100)
print("Traing: ",np.bincount(y_train)/float(len(y_train))*100)
print("Test : ",np.bincount(y_test)/float(len(y_test))*100)

All:  [54.12541254 45.87458746]
Traing:  [54.30463576 45.69536424]
Test :  [53.94736842 46.05263158]


In [115]:
from sklearn.ensemble import RandomForestClassifier

In [116]:
random=RandomForestClassifier(n_estimators = 40, criterion = 'entropy', random_state = 123)

In [117]:
random.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=40, random_state=123)

In [118]:
y_predict=random.predict(X_test)
y_predict

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0],
      dtype=int64)

In [119]:
print(np.sum(y_test==y_predict))

103


In [120]:
print("Correct Sample Accuracy")
correct_idx=np.where(y_test==y_predict)
correct_idx

Correct Sample Accuracy


(array([  2,   4,   5,   6,   7,  10,  16,  17,  18,  20,  21,  22,  23,
         25,  26,  27,  28,  31,  32,  34,  35,  37,  38,  40,  41,  42,
         43,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  56,  57,
         58,  59,  60,  63,  65,  69,  72,  75,  76,  77,  78,  79,  80,
         82,  84,  86,  88,  89,  90,  91,  92,  93,  94,  95,  97,  98,
        100, 101, 102, 105, 107, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 121, 122, 124, 125, 127, 130, 131, 134, 135, 136,
        137, 139, 140, 141, 142, 144, 145, 146, 148, 149, 150, 151],
       dtype=int64),)

In [121]:
print("Incorrect Sample Accuracy")
Incorrect_idx=np.where(y_test!=y_predict)
Incorrect_idx

Incorrect Sample Accuracy


(array([  0,   1,   3,   8,   9,  11,  12,  13,  14,  15,  19,  24,  29,
         30,  33,  36,  39,  44,  55,  61,  62,  64,  66,  67,  68,  70,
         71,  73,  74,  81,  83,  85,  87,  96,  99, 103, 104, 106, 108,
        120, 123, 126, 128, 129, 132, 133, 138, 143, 147], dtype=int64),)

In [122]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.67      0.79      0.73        82
           1       0.69      0.54      0.61        70

    accuracy                           0.68       152
   macro avg       0.68      0.67      0.67       152
weighted avg       0.68      0.68      0.67       152



In [123]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_predict))

0.6776315789473685


In [124]:
for n in np.unique(y_test):
    idx=np.where(y_test==n)[0]
    plt.scatter(X_test[idx,1],X_test[idx,2],label="Class %s"% str(n))
plt.scatter(X_test[Incorrect_idx,1],X_test[Incorrect_idx,2],color='darkred',
                       s=40)    
    
plt.xlabel("sepal width[cm]")   
plt.ylabel("petal length [cm]")   
plt.legend(loc=3)
plt.title("Iris Classification Result")
plt.show()